### PR TITLE
BugFix for Windows: open README with UTF-8

### PR DESCRIPTION
**Pull request by daquinoaldo**
*Thanks for contributing to our bot* 😁❤️
*We really appreciate your effort!*

### Checklist:

* [x] Have you tested the bot locally?
* [x] Have you checked the logs?
* [x] Have you commented your code?

### CODE REVIEW

**Comment by domenicoblanco** [comment]
There are some conflicts on your PR. Can you update it?

**Comment by daquinoaldo** [comment]
Yes, I know... Is an old PR. I'll fix ASAP (hopefully on Monday).

**Comment by domenicoblanco** [comment]
Awesome, thanks!

**Comment by daquinoaldo** [comment]
Implemented manually in 8ea9137.

**Pull request closed without merging**
